### ISSUE TITLE
Issue when the player is activated in the application access

### ISSUE THREAD

**Issue by cadilhon** [supermat/PluginDomoticzFreebox#19]
After the activation of : "Contrôle du Freebox Player" i see this problem : 

2022-12-05 13:08:45.912 Error: Freebox: onHeartbeat error: 'id'
2022-12-05 13:08:45.913 Error: Freebox: Traceback (most recent call last):
2022-12-05 13:08:45.913 File "/home/pi/domoticz/plugins/PluginDomoticzFreebox/plugin.py", line 744, in onHeartbeat
2022-12-05 13:08:45.913 self._refresh_devices_players(f)
2022-12-05 13:08:45.913 File "/home/pi/domoticz/plugins/PluginDomoticzFreebox/plugin.py", line 583, in _refresh_devices_players
2022-12-05 13:08:45.913 uid = str(player['id'])
2022-12-05 13:08:45.913 KeyError: 'id'

**Comment by Abidos14** [comment]
Hello,

Exactly the same error for me with Freebox Pop :
 2023-01-06 14:09:10.744 Error: Freebox: onHeartbeat error: 'id'
2023-01-06 14:09:10.745 Error: Freebox: Traceback (most recent call last):
2023-01-06 14:09:10.745 File "/home/pi/domoticz/plugins/PluginDomoticzFreebox/plugin.py", line 744, in onHeartbeat
2023-01-06 14:09:10.745 self._refresh_devices_players(f)
2023-01-06 14:09:10.745 File "/home/pi/domoticz/plugins/PluginDomoticzFreebox/plugin.py", line 583, in _refresh_devices_players
2023-01-06 14:09:10.745 uid = str(player['id'])
2023-01-06 14:09:10.745 KeyError: 'id'
2023-01-06 14:09:10.745 

I read it was due ti the API... Is there any way to bypass the API and give a "false" id to the player ?
